[package]
name = "university-muenster-bachelor-thesis"
entrypoint = "lib.typ"
description = "Unofficial template for writing a bachelor's thesis at the University of Münster."
categories = ["thesis"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
