[package]
name = "university-muenster-master-thesis"
entrypoint = "lib.typ"
description = "Unofficial template for writing a master's thesis at the University of Münster."
categories = ["thesis"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
