[package]
name = "university-muenster-report"
entrypoint = "lib.typ"
description = "Unofficial template for writing a report at the University of Münster."
categories = ["report"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
